name: test

on:
  workflow_dispatch:
  pull_request:
  push:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: install wasi-sdk
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: WebAssembly/wasi-sdk
          platform: linux
          tag: 20.0
          cache: enable
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: wabt python3 python3-pip
          version: 1.0
      - name: build application
        run: make build